



// var fastCsv = Meteor.npmRequire('fast-csv');
// var jsZip = Meteor.npmRequire('jszip');
// var zip = new jsZip();


// Meteor.methods({
//   exportData: function(userId) {

// 	var getRequests = Requests.find().fetch;
// 	var exportRequestssAsCsv = function(userId) {
	  
// 	  // check(userId, String);
// 	  // var csvStream = csv.createWriteStream({headers: true}),
// 	  // writableStream = fs.createWriteStream("output.csv");
		 
// 	  // writableStream.on("finish", function(){
// 	  //   console.log("DONE!");
// 	  // });

// 	  var csv = fastCsv;
// 	  csv.writeToString( getRequests, 
// 	  {
// 		headers: true
// 	  }, 
// 	  function(error, data) 
// 	  {
// 		 if (error) {
// 		 return console.log(error);
// 		 } else {
// 		 return zip.file('Requests.csv', data);
// 	  }
// 	 });

// 	 return zip.generate({ type: "base64" });
//     }
// 	 exportRequestssAsCsv();
//   }
// });






// /*
//   Export
//   Method for handling data export from our app.
//  */


//   Import our NPM packages using the meteorhacks:npm package (thanks, Arunoda!).
//   See: https://atmospherejs.com/meteorhacks/npm.

//   The final require, 'fs', is using the core Npm.require method to pull in the
//   file system from Node.js core. We're doing this because fs is not an npm
//   package that we need to load. It's already available via Meteor, we just need
//   to tell Meteor to give us access to it here.
 
// // var fastCsv, jsZip, xmlBuilder;

// // jsZip = Meteor.npmRequire('jszip');

// // xmlBuilder = Meteor.npmRequire('xmlbuilder');

// // fastCsv = Meteor.npmRequire('fast-csv');

// // Meteor.methods({
// //   exportData: function(userId) {
// //     var assetsFolder, exportFriendsAsCsv, exportProfileAsHtml, exportProfileAsJSON, exportProfileAsXml, getComments, getFriends, getPosts, getUser, zip;
// //     check(userId, String);
// //     zip = new jsZip();
// //     assetsFolder = zip.folder('assets');
    
// //     exportFriendsAsCsv = function() {

// //       /*
// //         Export friends as a .csv file.
// //        */
// //       var csv;
// //       csv = fastCsv;
// //       return csv.writeToString(getFriends, {
// //         headers: true
// //       }, function(error, data) {
// //         if (error) {
// //           return console.log(error);
// //         } else {
// //           return zip.file('friends.csv', data);
// //         }
// //       });
// //     };
    
// //     exportFriendsAsCsv();
// //     return zip.generate({
// //       type: "base64"
// //     });
// //   }
// // });

// // ---
// // generated by coffee-script 1.9.2